name: Mobile Sync to Elge
on:
  push:
    paths:
      - 'src/elge/**' # Only triggers when you change the engine folder
jobs:
  push-to-elge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push Subfolder to Elge Repo
        run: |
          git remote add elge https://x-access-token:${{ secrets.SYNC_TOKEN }}@://
          github.com
          git subtree push --prefix=src/elge elge main
          
